# Generated by Django 3.0.4 on 2020-11-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201108_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avialble',
            new_name='available',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='place',
        ),
    ]
