# Generated by Django 3.0.4 on 2020-11-09 12:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CerditCard',
            new_name='CreditCard',
        ),
    ]
