# Generated by Django 3.0.4 on 2020-11-09 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0004_accountcategory_accountsubcategory_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='expenditure',
        ),
        migrations.AddField(
            model_name='bank',
            name='type',
            field=models.CharField(choices=[('bank', 'bank'), ('credit', 'credit')], default='bank', max_length=9),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='due',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=7)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=30)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.Bank')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.Category')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.Subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
