# Generated by Django 3.0.4 on 2020-11-10 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0006_auto_20201109_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('payment', 'payment'), ('expense', 'expense')], max_length=7)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=30)),
                ('payed', models.BooleanField(default=False)),
                ('emi_remaining', models.IntegerField(default=0)),
                ('balance_remaning', models.IntegerField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.CreditCard')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.Category')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.Subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
