# Generated by Django 3.0.4 on 2020-11-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_creditcardrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardrecord',
            name='emi_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditcardrecord',
            name='balance_remaning',
            field=models.IntegerField(default=0),
        ),
    ]
