# Generated by Django 3.0.4 on 2020-11-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_auto_20201110_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardrecord',
            old_name='create_on',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='creditcardrecord',
            name='emi_remaining',
        ),
    ]
