# Generated by Django 3.0.4 on 2020-11-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_auto_20201113_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardrecord',
            name='eccess',
            field=models.IntegerField(default=0),
        ),
    ]
