# Generated by Django 3.0.4 on 2020-11-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_creditcardrecord_eccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardrecord',
            name='eccess',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='eccess',
            field=models.IntegerField(default=0),
        ),
    ]
