# Generated by Django 3.0.4 on 2020-11-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_auto_20201113_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='eccess',
            new_name='excess',
        ),
    ]
